-- Table: CHALLENGES
CREATE TABLE CHALLENGES (
   ID int  NOT NULL DEFAULT seq.nextval,
   DEFINITION varchar(5000)  NOT NULL,
   STARTED timestamp  NOT NULL,
   FINISHED timestamp  NULL,
   TITLE varchar(500)  NOT NULL,
   CONSTRAINT CHALLENGES_pk PRIMARY KEY (ID)
);